const killers = [
  { name: 'Michael Myers',
   image : './assets/halloween.jpg',
   killCount : 121,
   wiki : 'https://en.wikipedia.org/wiki/Michael_Myers_(Halloween)',
   rottenTomatoes : 'https://www.rottentomatoes.com/m/1009113-halloween',
   films : 'https://www.imdb.com/list/ls066334100/',
   totalFilms : 11
 },
 { name: 'Jason Vorhees',
  image : './assets/jason.jpg',
  killCount : 157,
  wiki : 'https://en.wikipedia.org/wiki/Jason_Voorhees',
  rottenTomatoes : 'https://www.rottentomatoes.com/m/friday_the_13th_part_1',
  films : 'https://www.imdb.com/list/ls009545302/',
  totalFilms : 13
},
{ name: 'Freddy Krueger',
 image : './assets/freddy.jpg',
 killCount : 39,
 wiki : 'https://en.wikipedia.org/wiki/Freddy_Krueger',
 rottenTomatoes : 'https://www.rottentomatoes.com/m/nightmare_on_elm_street',
 films : 'https://www.imdb.com/list/ls009545233/',
 totalFilms : 11
},
{ name: 'Chucky',
 image : './assets/chucky.png',
 killCount : 38,
 wiki : 'https://en.wikipedia.org/wiki/Chucky_(character)',
 rottenTomatoes : 'https://www.rottentomatoes.com/m/cult_of_chucky',
 films : 'https://www.imdb.com/list/ls027750182/',
 totalFilms : 7
},
{ name: 'Jigsaw',
 image : './assets/saw.jpg',
 killCount : 60,
 wiki : 'https://en.wikipedia.org/wiki/Jigsaw_(Saw_character)',
 rottenTomatoes : 'https://www.rottentomatoes.com/m/saw',
 films : 'https://www.imdb.com/list/ls071983564/',
 totalFilms : 9
},
{ name: 'Pinhead',
 image : './assets/pinhead.jpg',
 killCount : 35,
 wiki : 'https://en.wikipedia.org/wiki/Pinhead_(Hellraiser)',
 rottenTomatoes : 'https://www.rottentomatoes.com/m/hellraiser/reviews',
 films : 'https://www.imdb.com/list/ls064242940/',
 totalFilms : 34
},
{ name: 'Leatherface',
 image : './assets/leatherface.jpg',
 killCount : 14,
 wiki : 'https://en.wikipedia.org/wiki/Leatherface',
 rottenTomatoes : 'https://www.rottentomatoes.com/m/1021112-texas_chainsaw_massacre',
 films : 'https://www.imdb.com/list/ls000681853/',
 totalFilms : 6
},
{ name: 'Jack Frost',
 image : './assets/jackfrost.jpg',
 killCount : 10,
 wiki : 'https://en.wikipedia.org/wiki/Jack_Frost_(1997_film)',
 rottenTomatoes : 'https://www.rottentomatoes.com/m/1077660-jack_frost',
 films : 'https://www.imdb.com/title/tt0116671/',
 totalFilms : 2
},
]
